export const projectsData = [
    {
      id: 1,
      titleKey: "project_1_title",
      descriptionKey: "project_1_description",
      technologies: [
        "React",
        "Node.js",
        "HTML",
        "CSS",
        "JavaScript",
        "TypeScript",
        "Chakra UI",
        "Slack",
      ],
      githubUrl: "https://github.com/fsevindik/React_ToDo",
    },
    {
      id: 2,
      titleKey: "project_2_title",
      descriptionKey: "project_2_description",
      technologies: ["React", "Tailwind CSS", "TypeScript", "Chackra UI"],
      githubUrl: "https://github.com/fsevindik/clone-Story-Estimate/tree/main",
    },
    {
      id: 3,
      titleKey: "project_3_title",
      descriptionKey: "project_3_description",
      technologies: [
        "Next.js",
        "TypeScript",
        "Tailwind CSS",
        "Next Auth",
        "MongoDB",
        "Node",
        "bcrypt",
        "prisma",
        "react-hook-form",
        "react-icons",
      ],
      githubUrl: "https://github.com/fsevindik/ecommerce",
    },
    {
      id: 4,
      titleKey: "project_4_title",
      descriptionKey: "project_4_description",
      technologies: [
        "MongoDB",
        "Express",
        "React",
        "Node.js",
        "Tailwind CSS",
        "..and the more",
      ],
      githubUrl: "https://github.com/fsevindik/blog",
    },
  ];